/**
 * js/payment.js
 * ─────────────────────────────────────────────────────────────────────────────
 * Payment Service module for DviPlex website.
 * Prepares the frontend for future Razorpay API/Backend connection.
 */

import { CONFIG } from './config.js';

/**
 * Start the payment checkout process.
 * Later, this function will call the Cloudflare Pages Functions payment API,
 * generate a Razorpay order, trigger the Razorpay checkout overlay modal,
 * and await payment verification.
 *
 * @param {object} order - Clean order payload (excluding uploaded image URLs)
 * @returns {Promise<{ success: boolean, paymentId: string, orderId: string }>}
 */
export async function startPayment(order) {
  if (!order) {
    throw new Error('Invalid order payload for checkout.');
  }

  try {
    console.log('[Payment Service] Triggering checkout flow for order:', order);

    // Prepare to POST order details to payment gateway handler
    const response = await fetch(CONFIG.PAYMENT_ENDPOINT, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        amount: order.product_price,
        customerName: order.name,
        email: order.email,
        whatsapp: order.whatsapp_number
      })
    });

    if (response.ok) {
      const data = await response.json();
      return {
        success: data.success ?? true,
        paymentId: data.paymentId || `PAY_GATE_${Date.now()}`,
        orderId: data.orderId || ''
      };
    }

    // Fallback: If endpoint doesn't exist yet (404/500/etc.), return mock success
    // to keep the frontend operational for development.
    console.warn(`[Payment Service] Endpoint (${CONFIG.PAYMENT_ENDPOINT}) not available. Falling back to mock payment.`);
    return await simulatePaymentFlow(order);

  } catch (err) {
    console.warn('[Payment Service] Network connection failed. Simulating local mock payment.', err);
    return await simulatePaymentFlow(order);
  }
}

/**
 * Simulate payment gateway delay.
 * Returns confirmation details.
 */
function simulatePaymentFlow(order) {
  return new Promise((resolve) => {
    // Simulated short gateway response delay (0.8 s)
    setTimeout(() => {
      resolve({
        success: true,
        paymentId: `PAY_MOCK_${Math.random().toString(36).substr(2, 9).toUpperCase()}`,
        orderId: '' // Left blank, to be generated by sheets/save-order backend
      });
    }, 800);
  });
}
