const PRODUCTS_CATALOG = [
  {
    "category": "anime portrait",
    "categoryName": "Anime Portrait",
    "subfolder": "Cat",
    "title": "Custom Cat Anime Portrait",
    "media": [
      "Products/Anime/Cat/1.png",
      "Products/Anime/Cat/2.png",
      "Products/Anime/Cat/3.png",
      "Products/Anime/Cat/4.png",
      "Products/Anime/Cat/5.png",
      "Products/Anime/Cat/6.png",
      "Products/Anime/Cat/7.png"
    ],
    "thumbnail": "Products/Anime/Cat/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.4,
    "reviews": 26,
    "description": "A stunning, personalized Japanese anime-style portrait featuring your beloved cat. Handcrafted with clean line art, vibrant cell shading, and custom aesthetic backgrounds."
  },
  {
    "category": "anime portrait",
    "categoryName": "Anime Portrait",
    "subfolder": "Couple",
    "title": "Custom Couple Anime Portrait",
    "media": [
      "Products/Anime/Couple/1.png",
      "Products/Anime/Couple/2.png",
      "Products/Anime/Couple/3.png",
      "Products/Anime/Couple/4.png",
      "Products/Anime/Couple/5.png",
      "Products/Anime/Couple/6.png",
      "Products/Anime/Couple/7.png"
    ],
    "thumbnail": "Products/Anime/Couple/1.png",
    "originalPrice": 299,
    "price": 149,
    "rating": 4.4,
    "reviews": 78,
    "description": "A stunning, personalized Japanese anime-style portrait featuring you and your partner as a couple. Handcrafted with clean line art, vibrant cell shading, and custom aesthetic backgrounds."
  },
  {
    "category": "anime portrait",
    "categoryName": "Anime Portrait",
    "subfolder": "Dog",
    "title": "Custom Dog Anime Portrait",
    "media": [
      "Products/Anime/Dog/1.png",
      "Products/Anime/Dog/2.png",
      "Products/Anime/Dog/3.png",
      "Products/Anime/Dog/4.png",
      "Products/Anime/Dog/5.png",
      "Products/Anime/Dog/6.png",
      "Products/Anime/Dog/7.png"
    ],
    "thumbnail": "Products/Anime/Dog/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.6,
    "reviews": 28,
    "description": "A stunning, personalized Japanese anime-style portrait featuring your beloved dog. Handcrafted with clean line art, vibrant cell shading, and custom aesthetic backgrounds."
  },
  {
    "category": "anime portrait",
    "categoryName": "Anime Portrait",
    "subfolder": "Family",
    "title": "Custom Family Anime Portrait",
    "media": [
      "Products/Anime/Family/1.png",
      "Products/Anime/Family/2.png",
      "Products/Anime/Family/3.png",
      "Products/Anime/Family/4.png",
      "Products/Anime/Family/5.png",
      "Products/Anime/Family/6.png",
      "Products/Anime/Family/7.png"
    ],
    "thumbnail": "Products/Anime/Family/1.png",
    "originalPrice": 299,
    "price": 149,
    "rating": 4.5,
    "reviews": 72,
    "description": "A stunning, personalized Japanese anime-style portrait featuring your beautiful family. Handcrafted with clean line art, vibrant cell shading, and custom aesthetic backgrounds."
  },
  {
    "category": "anime portrait",
    "categoryName": "Anime Portrait",
    "subfolder": "Friends",
    "title": "Custom Friends Anime Portrait",
    "media": [
      "Products/Anime/Friends/1.png",
      "Products/Anime/Friends/2.png",
      "Products/Anime/Friends/3.png",
      "Products/Anime/Friends/4.png",
      "Products/Anime/Friends/5.png",
      "Products/Anime/Friends/6.png",
      "Products/Anime/Friends/7.png"
    ],
    "thumbnail": "Products/Anime/Friends/1.png",
    "originalPrice": 299,
    "price": 149,
    "rating": 4.5,
    "reviews": 35,
    "description": "A stunning, personalized Japanese anime-style portrait featuring you and your closest friends. Handcrafted with clean line art, vibrant cell shading, and custom aesthetic backgrounds."
  },
  {
    "category": "anime portrait",
    "categoryName": "Anime Portrait",
    "subfolder": "GamerBoy",
    "title": "Custom Gamer Boy Anime Portrait",
    "media": [
      "Products/Anime/GamerBoy/1.png",
      "Products/Anime/GamerBoy/2.png",
      "Products/Anime/GamerBoy/3.png",
      "Products/Anime/GamerBoy/4.png",
      "Products/Anime/GamerBoy/5.png",
      "Products/Anime/GamerBoy/6.png",
      "Products/Anime/GamerBoy/7.png"
    ],
    "thumbnail": "Products/Anime/GamerBoy/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.7,
    "reviews": 71,
    "description": "A stunning, personalized Japanese anime-style portrait featuring a gentleman. Handcrafted with clean line art, vibrant cell shading, and custom aesthetic backgrounds."
  },
  {
    "category": "anime portrait",
    "categoryName": "Anime Portrait",
    "subfolder": "GamerGirl",
    "title": "Custom Gamer Girl Anime Portrait",
    "media": [
      "Products/Anime/GamerGirl/1.png",
      "Products/Anime/GamerGirl/2.png",
      "Products/Anime/GamerGirl/3.png",
      "Products/Anime/GamerGirl/4.png",
      "Products/Anime/GamerGirl/5.png",
      "Products/Anime/GamerGirl/6.png",
      "Products/Anime/GamerGirl/7.png"
    ],
    "thumbnail": "Products/Anime/GamerGirl/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.2,
    "reviews": 29,
    "description": "A stunning, personalized Japanese anime-style portrait featuring a lady. Handcrafted with clean line art, vibrant cell shading, and custom aesthetic backgrounds."
  },
  {
    "category": "anime portrait",
    "categoryName": "Anime Portrait",
    "subfolder": "Man",
    "title": "Custom Man Anime Portrait",
    "media": [
      "Products/Anime/Man/1.png",
      "Products/Anime/Man/2.png",
      "Products/Anime/Man/3.png",
      "Products/Anime/Man/4.png",
      "Products/Anime/Man/5.png",
      "Products/Anime/Man/6.png",
      "Products/Anime/Man/7.png"
    ],
    "thumbnail": "Products/Anime/Man/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.8,
    "reviews": 30,
    "description": "A stunning, personalized Japanese anime-style portrait featuring a gentleman. Handcrafted with clean line art, vibrant cell shading, and custom aesthetic backgrounds."
  },
  {
    "category": "anime portrait",
    "categoryName": "Anime Portrait",
    "subfolder": "Person With Cat",
    "title": "Custom Person with Cat Anime Portrait",
    "media": [
      "Products/Anime/Person With Cat/1.png",
      "Products/Anime/Person With Cat/2.png",
      "Products/Anime/Person With Cat/3.png",
      "Products/Anime/Person With Cat/4.png",
      "Products/Anime/Person With Cat/5.png",
      "Products/Anime/Person With Cat/6.png",
      "Products/Anime/Person With Cat/7.png"
    ],
    "thumbnail": "Products/Anime/Person With Cat/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.2,
    "reviews": 29,
    "description": "A stunning, personalized Japanese anime-style portrait featuring your beloved person with cat. Handcrafted with clean line art, vibrant cell shading, and custom aesthetic backgrounds."
  },
  {
    "category": "anime portrait",
    "categoryName": "Anime Portrait",
    "subfolder": "Person With Dog",
    "title": "Custom Person with Dog Anime Portrait",
    "media": [
      "Products/Anime/Person With Dog/1.png",
      "Products/Anime/Person With Dog/2.png",
      "Products/Anime/Person With Dog/3.png",
      "Products/Anime/Person With Dog/4.png",
      "Products/Anime/Person With Dog/5.png",
      "Products/Anime/Person With Dog/6.png",
      "Products/Anime/Person With Dog/7.png"
    ],
    "thumbnail": "Products/Anime/Person With Dog/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.4,
    "reviews": 31,
    "description": "A stunning, personalized Japanese anime-style portrait featuring your beloved person with dog. Handcrafted with clean line art, vibrant cell shading, and custom aesthetic backgrounds."
  },
  {
    "category": "anime portrait",
    "categoryName": "Anime Portrait",
    "subfolder": "Sibling",
    "title": "Custom Sibling Anime Portrait",
    "media": [
      "Products/Anime/Sibling/1.png",
      "Products/Anime/Sibling/2.png",
      "Products/Anime/Sibling/3.png",
      "Products/Anime/Sibling/4.png",
      "Products/Anime/Sibling/5.png",
      "Products/Anime/Sibling/6.png",
      "Products/Anime/Sibling/7.png"
    ],
    "thumbnail": "Products/Anime/Sibling/1.png",
    "originalPrice": 299,
    "price": 149,
    "rating": 4.2,
    "reviews": 32,
    "description": "A stunning, personalized Japanese anime-style portrait featuring siblings. Handcrafted with clean line art, vibrant cell shading, and custom aesthetic backgrounds."
  },
  {
    "category": "anime portrait",
    "categoryName": "Anime Portrait",
    "subfolder": "Woman",
    "title": "Custom Woman Anime Portrait",
    "media": [
      "Products/Anime/Woman/1.png",
      "Products/Anime/Woman/2.png",
      "Products/Anime/Woman/3.png",
      "Products/Anime/Woman/4.png",
      "Products/Anime/Woman/5.png",
      "Products/Anime/Woman/6.png",
      "Products/Anime/Woman/7.png"
    ],
    "thumbnail": "Products/Anime/Woman/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.7,
    "reviews": 47,
    "description": "A stunning, personalized Japanese anime-style portrait featuring a gentleman. Handcrafted with clean line art, vibrant cell shading, and custom aesthetic backgrounds."
  },
  {
    "category": "caricature",
    "categoryName": "Caricature Portrait",
    "subfolder": "Birthday gift",
    "title": "Custom Birthday Gift Caricature Portrait",
    "media": [
      "Products/Caricature/Birthday gift/1.png",
      "Products/Caricature/Birthday gift/2.png",
      "Products/Caricature/Birthday gift/3.png",
      "Products/Caricature/Birthday gift/4.png",
      "Products/Caricature/Birthday gift/5.png",
      "Products/Caricature/Birthday gift/6.png",
      "Products/Caricature/Birthday gift/7.png"
    ],
    "thumbnail": "Products/Caricature/Birthday gift/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.5,
    "reviews": 41,
    "description": "A fun, cartoon caricature portrait of a custom birthday gift illustration full of personality and humor. Hand-drawn by professional artists, emphasizing key features for a delightful custom gift."
  },
  {
    "category": "caricature",
    "categoryName": "Caricature Portrait",
    "subfolder": "Cat",
    "title": "Custom Cat Caricature Portrait",
    "media": [
      "Products/Caricature/Cat/1.png",
      "Products/Caricature/Cat/2.png",
      "Products/Caricature/Cat/3.png",
      "Products/Caricature/Cat/4.png",
      "Products/Caricature/Cat/5.png",
      "Products/Caricature/Cat/6.png",
      "Products/Caricature/Cat/7.png"
    ],
    "thumbnail": "Products/Caricature/Cat/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.2,
    "reviews": 66,
    "description": "A fun, cartoon caricature portrait of your beloved cat full of personality and humor. Hand-drawn by professional artists, emphasizing key features for a delightful custom gift."
  },
  {
    "category": "caricature",
    "categoryName": "Caricature Portrait",
    "subfolder": "Couple",
    "title": "Custom Couple Caricature Portrait",
    "media": [
      "Products/Caricature/Couple/1.png",
      "Products/Caricature/Couple/2.png",
      "Products/Caricature/Couple/3.png",
      "Products/Caricature/Couple/4.png",
      "Products/Caricature/Couple/5.png",
      "Products/Caricature/Couple/6.png",
      "Products/Caricature/Couple/7.png"
    ],
    "thumbnail": "Products/Caricature/Couple/1.png",
    "originalPrice": 299,
    "price": 149,
    "rating": 4.2,
    "reviews": 47,
    "description": "A fun, cartoon caricature portrait of you and your partner as a couple full of personality and humor. Hand-drawn by professional artists, emphasizing key features for a delightful custom gift."
  },
  {
    "category": "caricature",
    "categoryName": "Caricature Portrait",
    "subfolder": "Dog",
    "title": "Custom Dog Caricature Portrait",
    "media": [
      "Products/Caricature/Dog/1.png",
      "Products/Caricature/Dog/2.png",
      "Products/Caricature/Dog/3.png",
      "Products/Caricature/Dog/4.png",
      "Products/Caricature/Dog/5.png",
      "Products/Caricature/Dog/6.png",
      "Products/Caricature/Dog/7.png"
    ],
    "thumbnail": "Products/Caricature/Dog/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.4,
    "reviews": 68,
    "description": "A fun, cartoon caricature portrait of your beloved dog full of personality and humor. Hand-drawn by professional artists, emphasizing key features for a delightful custom gift."
  },
  {
    "category": "caricature",
    "categoryName": "Caricature Portrait",
    "subfolder": "Family",
    "title": "Custom Family Caricature Portrait",
    "media": [
      "Products/Caricature/Family/1.png",
      "Products/Caricature/Family/2.png",
      "Products/Caricature/Family/3.png",
      "Products/Caricature/Family/4.png",
      "Products/Caricature/Family/5.png",
      "Products/Caricature/Family/6.png",
      "Products/Caricature/Family/7.png"
    ],
    "thumbnail": "Products/Caricature/Family/1.png",
    "originalPrice": 299,
    "price": 149,
    "rating": 4.3,
    "reviews": 41,
    "description": "A fun, cartoon caricature portrait of your beautiful family full of personality and humor. Hand-drawn by professional artists, emphasizing key features for a delightful custom gift."
  },
  {
    "category": "caricature",
    "categoryName": "Caricature Portrait",
    "subfolder": "Friends",
    "title": "Custom Friends Caricature Portrait",
    "media": [
      "Products/Caricature/Friends/1.png",
      "Products/Caricature/Friends/2.png",
      "Products/Caricature/Friends/3.png",
      "Products/Caricature/Friends/4.png",
      "Products/Caricature/Friends/5.png",
      "Products/Caricature/Friends/6.png",
      "Products/Caricature/Friends/7.png"
    ],
    "thumbnail": "Products/Caricature/Friends/1.png",
    "originalPrice": 299,
    "price": 149,
    "rating": 4.3,
    "reviews": 75,
    "description": "A fun, cartoon caricature portrait of you and your closest friends full of personality and humor. Hand-drawn by professional artists, emphasizing key features for a delightful custom gift."
  },
  {
    "category": "caricature",
    "categoryName": "Caricature Portrait",
    "subfolder": "Man",
    "title": "Custom Man Caricature Portrait",
    "media": [
      "Products/Caricature/Man/1.png",
      "Products/Caricature/Man/2.png",
      "Products/Caricature/Man/3.png",
      "Products/Caricature/Man/4.png",
      "Products/Caricature/Man/5.png",
      "Products/Caricature/Man/6.png",
      "Products/Caricature/Man/7.png"
    ],
    "thumbnail": "Products/Caricature/Man/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.6,
    "reviews": 70,
    "description": "A fun, cartoon caricature portrait of a gentleman full of personality and humor. Hand-drawn by professional artists, emphasizing key features for a delightful custom gift."
  },
  {
    "category": "caricature",
    "categoryName": "Caricature Portrait",
    "subfolder": "Person With Cat",
    "title": "Custom Person with Cat Caricature Portrait",
    "media": [
      "Products/Caricature/Person With Cat/1.png",
      "Products/Caricature/Person With Cat/2.png",
      "Products/Caricature/Person With Cat/3.png",
      "Products/Caricature/Person With Cat/4.png",
      "Products/Caricature/Person With Cat/5.png",
      "Products/Caricature/Person With Cat/6.png",
      "Products/Caricature/Person With Cat/7.png"
    ],
    "thumbnail": "Products/Caricature/Person With Cat/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.7,
    "reviews": 69,
    "description": "A fun, cartoon caricature portrait of your beloved person with cat full of personality and humor. Hand-drawn by professional artists, emphasizing key features for a delightful custom gift."
  },
  {
    "category": "caricature",
    "categoryName": "Caricature Portrait",
    "subfolder": "Person With Dog",
    "title": "Custom Person with Dog Caricature Portrait",
    "media": [
      "Products/Caricature/Person With Dog/1.png",
      "Products/Caricature/Person With Dog/2.png",
      "Products/Caricature/Person With Dog/3.png",
      "Products/Caricature/Person With Dog/4.png",
      "Products/Caricature/Person With Dog/5.png",
      "Products/Caricature/Person With Dog/6.png",
      "Products/Caricature/Person With Dog/7.png"
    ],
    "thumbnail": "Products/Caricature/Person With Dog/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.2,
    "reviews": 71,
    "description": "A fun, cartoon caricature portrait of your beloved person with dog full of personality and humor. Hand-drawn by professional artists, emphasizing key features for a delightful custom gift."
  },
  {
    "category": "caricature",
    "categoryName": "Caricature Portrait",
    "subfolder": "Professional",
    "title": "Custom Professional Caricature Portrait",
    "media": [
      "Products/Caricature/Professional/1.png",
      "Products/Caricature/Professional/2.png",
      "Products/Caricature/Professional/3.png",
      "Products/Caricature/Professional/4.png",
      "Products/Caricature/Professional/5.png",
      "Products/Caricature/Professional/6.png",
      "Products/Caricature/Professional/7.png"
    ],
    "thumbnail": "Products/Caricature/Professional/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.4,
    "reviews": 61,
    "description": "A fun, cartoon caricature portrait of a custom professional illustration full of personality and humor. Hand-drawn by professional artists, emphasizing key features for a delightful custom gift."
  },
  {
    "category": "caricature",
    "categoryName": "Caricature Portrait",
    "subfolder": "Siblings",
    "title": "Custom Siblings Caricature Portrait",
    "media": [
      "Products/Caricature/Siblings/1.png",
      "Products/Caricature/Siblings/2.png",
      "Products/Caricature/Siblings/3.png",
      "Products/Caricature/Siblings/4.png",
      "Products/Caricature/Siblings/5.png",
      "Products/Caricature/Siblings/6.png",
      "Products/Caricature/Siblings/7.png"
    ],
    "thumbnail": "Products/Caricature/Siblings/1.png",
    "originalPrice": 299,
    "price": 149,
    "rating": 4.3,
    "reviews": 45,
    "description": "A fun, cartoon caricature portrait of siblings full of personality and humor. Hand-drawn by professional artists, emphasizing key features for a delightful custom gift."
  },
  {
    "category": "caricature",
    "categoryName": "Caricature Portrait",
    "subfolder": "Women",
    "title": "Custom Women Caricature Portrait",
    "media": [
      "Products/Caricature/Women/1.png",
      "Products/Caricature/Women/2.png",
      "Products/Caricature/Women/3.png",
      "Products/Caricature/Women/4.png",
      "Products/Caricature/Women/5.png",
      "Products/Caricature/Women/6.png",
      "Products/Caricature/Women/7.png"
    ],
    "thumbnail": "Products/Caricature/Women/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.2,
    "reviews": 20,
    "description": "A fun, cartoon caricature portrait of a custom women illustration full of personality and humor. Hand-drawn by professional artists, emphasizing key features for a delightful custom gift."
  },
  {
    "category": "lineart",
    "categoryName": "Line Art Portrait",
    "subfolder": "Cat",
    "title": "Custom Cat Line Art Portrait",
    "media": [
      "Products/Line Art/Cat/1.png",
      "Products/Line Art/Cat/2.png",
      "Products/Line Art/Cat/3.png",
      "Products/Line Art/Cat/4.png",
      "Products/Line Art/Cat/5.png",
      "Products/Line Art/Cat/6.png",
      "Products/Line Art/Cat/7.png"
    ],
    "thumbnail": "Products/Line Art/Cat/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.2,
    "reviews": 42,
    "description": "A clean, elegant minimalist line art illustration featuring your beloved cat. Highlights shapes and details with artistic simplicity, perfect for modern home wall decor."
  },
  {
    "category": "lineart",
    "categoryName": "Line Art Portrait",
    "subfolder": "Couple",
    "title": "Custom Couple Line Art Portrait",
    "media": [
      "Products/Line Art/Couple/1.png",
      "Products/Line Art/Couple/2.png",
      "Products/Line Art/Couple/3.png",
      "Products/Line Art/Couple/4.png",
      "Products/Line Art/Couple/5.png",
      "Products/Line Art/Couple/6.png",
      "Products/Line Art/Couple/7.png"
    ],
    "thumbnail": "Products/Line Art/Couple/1.png",
    "originalPrice": 299,
    "price": 149,
    "rating": 4.2,
    "reviews": 23,
    "description": "A clean, elegant minimalist line art illustration featuring you and your partner as a couple. Highlights shapes and details with artistic simplicity, perfect for modern home wall decor."
  },
  {
    "category": "lineart",
    "categoryName": "Line Art Portrait",
    "subfolder": "Dog",
    "title": "Custom Dog Line Art Portrait",
    "media": [
      "Products/Line Art/Dog/1.png",
      "Products/Line Art/Dog/2.png",
      "Products/Line Art/Dog/3.png",
      "Products/Line Art/Dog/4.png",
      "Products/Line Art/Dog/5.png",
      "Products/Line Art/Dog/6.png",
      "Products/Line Art/Dog/7.png"
    ],
    "thumbnail": "Products/Line Art/Dog/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.4,
    "reviews": 44,
    "description": "A clean, elegant minimalist line art illustration featuring your beloved dog. Highlights shapes and details with artistic simplicity, perfect for modern home wall decor."
  },
  {
    "category": "lineart",
    "categoryName": "Line Art Portrait",
    "subfolder": "Family",
    "title": "Custom Family Line Art Portrait",
    "media": [
      "Products/Line Art/Family/1.png",
      "Products/Line Art/Family/2.png",
      "Products/Line Art/Family/3.png",
      "Products/Line Art/Family/4.png",
      "Products/Line Art/Family/5.png",
      "Products/Line Art/Family/6.png",
      "Products/Line Art/Family/7.png"
    ],
    "thumbnail": "Products/Line Art/Family/1.png",
    "originalPrice": 299,
    "price": 149,
    "rating": 4.3,
    "reviews": 17,
    "description": "A clean, elegant minimalist line art illustration featuring your beautiful family. Highlights shapes and details with artistic simplicity, perfect for modern home wall decor."
  },
  {
    "category": "lineart",
    "categoryName": "Line Art Portrait",
    "subfolder": "Friend",
    "title": "Custom Friend Line Art Portrait",
    "media": [
      "Products/Line Art/Friend/1.png",
      "Products/Line Art/Friend/2.png",
      "Products/Line Art/Friend/3.png",
      "Products/Line Art/Friend/4.png",
      "Products/Line Art/Friend/5.png",
      "Products/Line Art/Friend/6.png",
      "Products/Line Art/Friend/7.png"
    ],
    "thumbnail": "Products/Line Art/Friend/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.7,
    "reviews": 78,
    "description": "A clean, elegant minimalist line art illustration featuring a custom friend illustration. Highlights shapes and details with artistic simplicity, perfect for modern home wall decor."
  },
  {
    "category": "lineart",
    "categoryName": "Line Art Portrait",
    "subfolder": "GrandParents",
    "title": "Custom Grandparents Line Art Portrait",
    "media": [
      "Products/Line Art/GrandParents/1.png",
      "Products/Line Art/GrandParents/2.png",
      "Products/Line Art/GrandParents/3.png",
      "Products/Line Art/GrandParents/4.png",
      "Products/Line Art/GrandParents/5.png",
      "Products/Line Art/GrandParents/6.png",
      "Products/Line Art/GrandParents/7.png"
    ],
    "thumbnail": "Products/Line Art/GrandParents/1.png",
    "originalPrice": 299,
    "price": 149,
    "rating": 4.6,
    "reviews": 25,
    "description": "A clean, elegant minimalist line art illustration featuring your dear grandparents. Highlights shapes and details with artistic simplicity, perfect for modern home wall decor."
  },
  {
    "category": "lineart",
    "categoryName": "Line Art Portrait",
    "subfolder": "Man",
    "title": "Custom Man Line Art Portrait",
    "media": [
      "Products/Line Art/Man/1.png",
      "Products/Line Art/Man/2.png",
      "Products/Line Art/Man/3.png",
      "Products/Line Art/Man/4.png",
      "Products/Line Art/Man/5.png",
      "Products/Line Art/Man/6.png",
      "Products/Line Art/Man/7.png"
    ],
    "thumbnail": "Products/Line Art/Man/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.6,
    "reviews": 46,
    "description": "A clean, elegant minimalist line art illustration featuring a gentleman. Highlights shapes and details with artistic simplicity, perfect for modern home wall decor."
  },
  {
    "category": "lineart",
    "categoryName": "Line Art Portrait",
    "subfolder": "Person With Cat",
    "title": "Custom Person with Cat Line Art Portrait",
    "media": [
      "Products/Line Art/Person With Cat/1.png",
      "Products/Line Art/Person With Cat/2.png",
      "Products/Line Art/Person With Cat/3.png",
      "Products/Line Art/Person With Cat/4.png",
      "Products/Line Art/Person With Cat/5.png",
      "Products/Line Art/Person With Cat/6.png",
      "Products/Line Art/Person With Cat/7.png"
    ],
    "thumbnail": "Products/Line Art/Person With Cat/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.7,
    "reviews": 45,
    "description": "A clean, elegant minimalist line art illustration featuring your beloved person with cat. Highlights shapes and details with artistic simplicity, perfect for modern home wall decor."
  },
  {
    "category": "lineart",
    "categoryName": "Line Art Portrait",
    "subfolder": "Person with dog",
    "title": "Custom Person with Dog Line Art Portrait",
    "media": [
      "Products/Line Art/Person with dog/1.png",
      "Products/Line Art/Person with dog/2.png",
      "Products/Line Art/Person with dog/3.png",
      "Products/Line Art/Person with dog/4.png",
      "Products/Line Art/Person with dog/5.png",
      "Products/Line Art/Person with dog/6.png",
      "Products/Line Art/Person with dog/7.png"
    ],
    "thumbnail": "Products/Line Art/Person with dog/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.2,
    "reviews": 47,
    "description": "A clean, elegant minimalist line art illustration featuring your beloved person with dog. Highlights shapes and details with artistic simplicity, perfect for modern home wall decor."
  },
  {
    "category": "lineart",
    "categoryName": "Line Art Portrait",
    "subfolder": "Pregnent",
    "title": "Custom Pregnant Line Art Portrait",
    "media": [
      "Products/Line Art/Pregnent/1.png",
      "Products/Line Art/Pregnent/2.png",
      "Products/Line Art/Pregnent/3.png",
      "Products/Line Art/Pregnent/4.png",
      "Products/Line Art/Pregnent/5.png",
      "Products/Line Art/Pregnent/6.png",
      "Products/Line Art/Pregnent/7.png"
    ],
    "thumbnail": "Products/Line Art/Pregnent/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.7,
    "reviews": 25,
    "description": "A clean, elegant minimalist line art illustration featuring a custom pregnant illustration. Highlights shapes and details with artistic simplicity, perfect for modern home wall decor."
  },
  {
    "category": "lineart",
    "categoryName": "Line Art Portrait",
    "subfolder": "Sibling",
    "title": "Custom Sibling Line Art Portrait",
    "media": [
      "Products/Line Art/Sibling/1.png",
      "Products/Line Art/Sibling/2.png",
      "Products/Line Art/Sibling/3.png",
      "Products/Line Art/Sibling/4.png",
      "Products/Line Art/Sibling/5.png",
      "Products/Line Art/Sibling/6.png",
      "Products/Line Art/Sibling/7.png"
    ],
    "thumbnail": "Products/Line Art/Sibling/1.png",
    "originalPrice": 299,
    "price": 149,
    "rating": 4.7,
    "reviews": 48,
    "description": "A clean, elegant minimalist line art illustration featuring siblings. Highlights shapes and details with artistic simplicity, perfect for modern home wall decor."
  },
  {
    "category": "lineart",
    "categoryName": "Line Art Portrait",
    "subfolder": "Women",
    "title": "Custom Women Line Art Portrait",
    "media": [
      "Products/Line Art/Women/1.png",
      "Products/Line Art/Women/2.png",
      "Products/Line Art/Women/3.png",
      "Products/Line Art/Women/4.png",
      "Products/Line Art/Women/5.png",
      "Products/Line Art/Women/6.png",
      "Products/Line Art/Women/7.png"
    ],
    "thumbnail": "Products/Line Art/Women/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.2,
    "reviews": 67,
    "description": "A clean, elegant minimalist line art illustration featuring a custom women illustration. Highlights shapes and details with artistic simplicity, perfect for modern home wall decor."
  },
  {
    "category": "pet lineart",
    "categoryName": "Pet Line Art",
    "subfolder": "LP B Dog",
    "title": "Custom Black Dog Pet Line Art",
    "media": [
      "Products/Pet Line Art/LP B Dog/1.png",
      "Products/Pet Line Art/LP B Dog/2.png",
      "Products/Pet Line Art/LP B Dog/3.png",
      "Products/Pet Line Art/LP B Dog/4.png",
      "Products/Pet Line Art/LP B Dog/5.png",
      "Products/Pet Line Art/LP B Dog/6.png",
      "Products/Pet Line Art/LP B Dog/7.png",
      "Products/Pet Line Art/LP B Dog/8.png",
      "Products/Pet Line Art/LP B Dog/9.png"
    ],
    "thumbnail": "Products/Pet Line Art/LP B Dog/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.6,
    "reviews": 68,
    "description": "A sleek, minimalist line art portrait capturing the unique essence of your beloved black dog. Hand-drawn with thin lines on a solid color backdrop for a premium, contemporary design."
  },
  {
    "category": "pet lineart",
    "categoryName": "Pet Line Art",
    "subfolder": "LP Cat",
    "title": "Custom Cat Pet Line Art",
    "media": [
      "Products/Pet Line Art/LP Cat/1.png",
      "Products/Pet Line Art/LP Cat/2.png",
      "Products/Pet Line Art/LP Cat/3.png",
      "Products/Pet Line Art/LP Cat/4.png",
      "Products/Pet Line Art/LP Cat/5.png",
      "Products/Pet Line Art/LP Cat/6.png",
      "Products/Pet Line Art/LP Cat/7.png",
      "Products/Pet Line Art/LP Cat/8.png",
      "Products/Pet Line Art/LP Cat/9.png"
    ],
    "thumbnail": "Products/Pet Line Art/LP Cat/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.6,
    "reviews": 54,
    "description": "A sleek, minimalist line art portrait capturing the unique essence of your beloved cat. Hand-drawn with thin lines on a solid color backdrop for a premium, contemporary design."
  },
  {
    "category": "pet lineart",
    "categoryName": "Pet Line Art",
    "subfolder": "LP Dog",
    "title": "Custom Dog Pet Line Art",
    "media": [
      "Products/Pet Line Art/LP Dog/1.png",
      "Products/Pet Line Art/LP Dog/2.png",
      "Products/Pet Line Art/LP Dog/3.png",
      "Products/Pet Line Art/LP Dog/4.png",
      "Products/Pet Line Art/LP Dog/5.png",
      "Products/Pet Line Art/LP Dog/6.png",
      "Products/Pet Line Art/LP Dog/7.png",
      "Products/Pet Line Art/LP Dog/8.png",
      "Products/Pet Line Art/LP Dog/9.png"
    ],
    "thumbnail": "Products/Pet Line Art/LP Dog/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.8,
    "reviews": 56,
    "description": "A sleek, minimalist line art portrait capturing the unique essence of your beloved dog. Hand-drawn with thin lines on a solid color backdrop for a premium, contemporary design."
  },
  {
    "category": "pet lineart",
    "categoryName": "Pet Line Art",
    "subfolder": "LP GO Dog",
    "title": "Custom Gold Dog Pet Line Art",
    "media": [
      "Products/Pet Line Art/LP GO Dog/1.png",
      "Products/Pet Line Art/LP GO Dog/2.png",
      "Products/Pet Line Art/LP GO Dog/3.png",
      "Products/Pet Line Art/LP GO Dog/4.png",
      "Products/Pet Line Art/LP GO Dog/5.png",
      "Products/Pet Line Art/LP GO Dog/6.png",
      "Products/Pet Line Art/LP GO Dog/7.png",
      "Products/Pet Line Art/LP GO Dog/8.png",
      "Products/Pet Line Art/LP GO Dog/9.png"
    ],
    "thumbnail": "Products/Pet Line Art/LP GO Dog/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.3,
    "reviews": 52,
    "description": "A sleek, minimalist line art portrait capturing the unique essence of your beloved gold dog. Hand-drawn with thin lines on a solid color backdrop for a premium, contemporary design."
  },
  {
    "category": "pet lineart",
    "categoryName": "Pet Line Art",
    "subfolder": "LP GR Dog",
    "title": "Custom Green Dog Pet Line Art",
    "media": [
      "Products/Pet Line Art/LP GR Dog/1.png",
      "Products/Pet Line Art/LP GR Dog/2.png",
      "Products/Pet Line Art/LP GR Dog/3.png",
      "Products/Pet Line Art/LP GR Dog/4.png",
      "Products/Pet Line Art/LP GR Dog/5.png",
      "Products/Pet Line Art/LP GR Dog/6.png",
      "Products/Pet Line Art/LP GR Dog/7.png",
      "Products/Pet Line Art/LP GR Dog/8.png",
      "Products/Pet Line Art/LP GR Dog/9.png"
    ],
    "thumbnail": "Products/Pet Line Art/LP GR Dog/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.5,
    "reviews": 17,
    "description": "A sleek, minimalist line art portrait capturing the unique essence of your beloved green dog. Hand-drawn with thin lines on a solid color backdrop for a premium, contemporary design."
  },
  {
    "category": "pet lineart",
    "categoryName": "Pet Line Art",
    "subfolder": "LP L Dog",
    "title": "Custom Lavender Dog Pet Line Art",
    "media": [
      "Products/Pet Line Art/LP L Dog/1.png",
      "Products/Pet Line Art/LP L Dog/2.png",
      "Products/Pet Line Art/LP L Dog/3.png",
      "Products/Pet Line Art/LP L Dog/4.png",
      "Products/Pet Line Art/LP L Dog/5.png",
      "Products/Pet Line Art/LP L Dog/6.png",
      "Products/Pet Line Art/LP L Dog/7.png",
      "Products/Pet Line Art/LP L Dog/8.png",
      "Products/Pet Line Art/LP L Dog/9.png"
    ],
    "thumbnail": "Products/Pet Line Art/LP L Dog/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.3,
    "reviews": 53,
    "description": "A sleek, minimalist line art portrait capturing the unique essence of your beloved lavender dog. Hand-drawn with thin lines on a solid color backdrop for a premium, contemporary design."
  },
  {
    "category": "watercolor pastel",
    "categoryName": "Watercolor Pastel Portrait",
    "subfolder": "Cat",
    "title": "Custom Cat Watercolor Pastel Portrait",
    "media": [
      "Products/Water colour pastol/Cat/1.png",
      "Products/Water colour pastol/Cat/2.png",
      "Products/Water colour pastol/Cat/3.png",
      "Products/Water colour pastol/Cat/4.png",
      "Products/Water colour pastol/Cat/5.png",
      "Products/Water colour pastol/Cat/6.png",
      "Products/Water colour pastol/Cat/7.png"
    ],
    "thumbnail": "Products/Water colour pastol/Cat/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.3,
    "reviews": 36,
    "description": "A dreamy, soft watercolor pastel portrait illustrating your beloved cat. Painted with gentle brush strokes, light gradients, and warm textures for a cozy, premium display."
  },
  {
    "category": "watercolor pastel",
    "categoryName": "Watercolor Pastel Portrait",
    "subfolder": "Couple",
    "title": "Custom Couple Watercolor Pastel Portrait",
    "media": [
      "Products/Water colour pastol/Couple/1.png",
      "Products/Water colour pastol/Couple/2.png",
      "Products/Water colour pastol/Couple/3.png",
      "Products/Water colour pastol/Couple/4.png",
      "Products/Water colour pastol/Couple/5.png",
      "Products/Water colour pastol/Couple/6.png",
      "Products/Water colour pastol/Couple/7.png"
    ],
    "thumbnail": "Products/Water colour pastol/Couple/1.png",
    "originalPrice": 299,
    "price": 149,
    "rating": 4.3,
    "reviews": 17,
    "description": "A dreamy, soft watercolor pastel portrait illustrating you and your partner as a couple. Painted with gentle brush strokes, light gradients, and warm textures for a cozy, premium display."
  },
  {
    "category": "watercolor pastel",
    "categoryName": "Watercolor Pastel Portrait",
    "subfolder": "Dog",
    "title": "Custom Dog Watercolor Pastel Portrait",
    "media": [
      "Products/Water colour pastol/Dog/1.png",
      "Products/Water colour pastol/Dog/2.png",
      "Products/Water colour pastol/Dog/3.png",
      "Products/Water colour pastol/Dog/4.png",
      "Products/Water colour pastol/Dog/5.png",
      "Products/Water colour pastol/Dog/6.png",
      "Products/Water colour pastol/Dog/7.png"
    ],
    "thumbnail": "Products/Water colour pastol/Dog/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.5,
    "reviews": 38,
    "description": "A dreamy, soft watercolor pastel portrait illustrating your beloved dog. Painted with gentle brush strokes, light gradients, and warm textures for a cozy, premium display."
  },
  {
    "category": "watercolor pastel",
    "categoryName": "Watercolor Pastel Portrait",
    "subfolder": "Family",
    "title": "Custom Family Watercolor Pastel Portrait",
    "media": [
      "Products/Water colour pastol/Family/1.png",
      "Products/Water colour pastol/Family/2.png",
      "Products/Water colour pastol/Family/3.png",
      "Products/Water colour pastol/Family/4.png",
      "Products/Water colour pastol/Family/5.png",
      "Products/Water colour pastol/Family/6.png",
      "Products/Water colour pastol/Family/7.png"
    ],
    "thumbnail": "Products/Water colour pastol/Family/1.png",
    "originalPrice": 299,
    "price": 149,
    "rating": 4.4,
    "reviews": 82,
    "description": "A dreamy, soft watercolor pastel portrait illustrating your beautiful family. Painted with gentle brush strokes, light gradients, and warm textures for a cozy, premium display."
  },
  {
    "category": "watercolor pastel",
    "categoryName": "Watercolor Pastel Portrait",
    "subfolder": "Friends",
    "title": "Custom Friends Watercolor Pastel Portrait",
    "media": [
      "Products/Water colour pastol/Friends/1.png",
      "Products/Water colour pastol/Friends/2.png",
      "Products/Water colour pastol/Friends/3.png",
      "Products/Water colour pastol/Friends/4.png",
      "Products/Water colour pastol/Friends/5.png",
      "Products/Water colour pastol/Friends/6.png",
      "Products/Water colour pastol/Friends/7.png"
    ],
    "thumbnail": "Products/Water colour pastol/Friends/1.png",
    "originalPrice": 299,
    "price": 149,
    "rating": 4.4,
    "reviews": 45,
    "description": "A dreamy, soft watercolor pastel portrait illustrating you and your closest friends. Painted with gentle brush strokes, light gradients, and warm textures for a cozy, premium display."
  },
  {
    "category": "watercolor pastel",
    "categoryName": "Watercolor Pastel Portrait",
    "subfolder": "Grandparents",
    "title": "Custom Grandparents Watercolor Pastel Portrait",
    "media": [
      "Products/Water colour pastol/Grandparents/1.png",
      "Products/Water colour pastol/Grandparents/2.png",
      "Products/Water colour pastol/Grandparents/3.png",
      "Products/Water colour pastol/Grandparents/4.png",
      "Products/Water colour pastol/Grandparents/5.png",
      "Products/Water colour pastol/Grandparents/6.png",
      "Products/Water colour pastol/Grandparents/7.png"
    ],
    "thumbnail": "Products/Water colour pastol/Grandparents/1.png",
    "originalPrice": 299,
    "price": 149,
    "rating": 4.7,
    "reviews": 19,
    "description": "A dreamy, soft watercolor pastel portrait illustrating your dear grandparents. Painted with gentle brush strokes, light gradients, and warm textures for a cozy, premium display."
  },
  {
    "category": "watercolor pastel",
    "categoryName": "Watercolor Pastel Portrait",
    "subfolder": "Man",
    "title": "Custom Man Watercolor Pastel Portrait",
    "media": [
      "Products/Water colour pastol/Man/1.png",
      "Products/Water colour pastol/Man/2.png",
      "Products/Water colour pastol/Man/3.png",
      "Products/Water colour pastol/Man/4.png",
      "Products/Water colour pastol/Man/5.png",
      "Products/Water colour pastol/Man/6.png",
      "Products/Water colour pastol/Man/7.png"
    ],
    "thumbnail": "Products/Water colour pastol/Man/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.7,
    "reviews": 40,
    "description": "A dreamy, soft watercolor pastel portrait illustrating a gentleman. Painted with gentle brush strokes, light gradients, and warm textures for a cozy, premium display."
  },
  {
    "category": "watercolor pastel",
    "categoryName": "Watercolor Pastel Portrait",
    "subfolder": "Pergnent",
    "title": "Custom Pregnant Watercolor Pastel Portrait",
    "media": [
      "Products/Water colour pastol/Pergnent/1.png",
      "Products/Water colour pastol/Pergnent/2.png",
      "Products/Water colour pastol/Pergnent/3.png",
      "Products/Water colour pastol/Pergnent/4.png",
      "Products/Water colour pastol/Pergnent/5.png",
      "Products/Water colour pastol/Pergnent/6.png",
      "Products/Water colour pastol/Pergnent/7.png"
    ],
    "thumbnail": "Products/Water colour pastol/Pergnent/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.8,
    "reviews": 19,
    "description": "A dreamy, soft watercolor pastel portrait illustrating a custom pregnant illustration. Painted with gentle brush strokes, light gradients, and warm textures for a cozy, premium display."
  },
  {
    "category": "watercolor pastel",
    "categoryName": "Watercolor Pastel Portrait",
    "subfolder": "Person With Cat",
    "title": "Custom Person with Cat Watercolor Pastel Portrait",
    "media": [
      "Products/Water colour pastol/Person With Cat/1.png",
      "Products/Water colour pastol/Person With Cat/2.png",
      "Products/Water colour pastol/Person With Cat/3.png",
      "Products/Water colour pastol/Person With Cat/4.png",
      "Products/Water colour pastol/Person With Cat/5.png",
      "Products/Water colour pastol/Person With Cat/6.png",
      "Products/Water colour pastol/Person With Cat/7.png"
    ],
    "thumbnail": "Products/Water colour pastol/Person With Cat/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.8,
    "reviews": 39,
    "description": "A dreamy, soft watercolor pastel portrait illustrating your beloved person with cat. Painted with gentle brush strokes, light gradients, and warm textures for a cozy, premium display."
  },
  {
    "category": "watercolor pastel",
    "categoryName": "Watercolor Pastel Portrait",
    "subfolder": "Person With Dog",
    "title": "Custom Person with Dog Watercolor Pastel Portrait",
    "media": [
      "Products/Water colour pastol/Person With Dog/1.png",
      "Products/Water colour pastol/Person With Dog/2.png",
      "Products/Water colour pastol/Person With Dog/3.png",
      "Products/Water colour pastol/Person With Dog/4.png",
      "Products/Water colour pastol/Person With Dog/5.png",
      "Products/Water colour pastol/Person With Dog/6.png",
      "Products/Water colour pastol/Person With Dog/7.png"
    ],
    "thumbnail": "Products/Water colour pastol/Person With Dog/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.3,
    "reviews": 41,
    "description": "A dreamy, soft watercolor pastel portrait illustrating your beloved person with dog. Painted with gentle brush strokes, light gradients, and warm textures for a cozy, premium display."
  },
  {
    "category": "watercolor pastel",
    "categoryName": "Watercolor Pastel Portrait",
    "subfolder": "Woman",
    "title": "Custom Woman Watercolor Pastel Portrait",
    "media": [
      "Products/Water colour pastol/Woman/1.png",
      "Products/Water colour pastol/Woman/2.png",
      "Products/Water colour pastol/Woman/3.png",
      "Products/Water colour pastol/Woman/4.png",
      "Products/Water colour pastol/Woman/5.png",
      "Products/Water colour pastol/Woman/6.png",
      "Products/Water colour pastol/Woman/7.png"
    ],
    "thumbnail": "Products/Water colour pastol/Woman/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.6,
    "reviews": 57,
    "description": "A dreamy, soft watercolor pastel portrait illustrating a gentleman. Painted with gentle brush strokes, light gradients, and warm textures for a cozy, premium display."
  },
  {
    "category": "watercolor splash",
    "categoryName": "Watercolor Splash Portrait",
    "subfolder": "Baby",
    "title": "Custom Baby Watercolor Splash Portrait",
    "media": [
      "Products/Water Splash/Baby/1.png",
      "Products/Water Splash/Baby/2.png",
      "Products/Water Splash/Baby/3.png",
      "Products/Water Splash/Baby/4.png",
      "Products/Water Splash/Baby/5.png",
      "Products/Water Splash/Baby/6.png",
      "Products/Water Splash/Baby/7.png"
    ],
    "thumbnail": "Products/Water Splash/Baby/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.2,
    "reviews": 69,
    "description": "An expressive, vibrant watercolor splash portrait of a sweet baby. Features bold organic paint splatters, rich textures, and bright color palettes for a modern artistic look."
  },
  {
    "category": "watercolor splash",
    "categoryName": "Watercolor Splash Portrait",
    "subfolder": "Cat",
    "title": "Custom Cat Watercolor Splash Portrait",
    "media": [
      "Products/Water Splash/Cat/1.png",
      "Products/Water Splash/Cat/2.png",
      "Products/Water Splash/Cat/3.png",
      "Products/Water Splash/Cat/4.png",
      "Products/Water Splash/Cat/5.png",
      "Products/Water Splash/Cat/6.png",
      "Products/Water Splash/Cat/7.png"
    ],
    "thumbnail": "Products/Water Splash/Cat/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.5,
    "reviews": 38,
    "description": "An expressive, vibrant watercolor splash portrait of your beloved cat. Features bold organic paint splatters, rich textures, and bright color palettes for a modern artistic look."
  },
  {
    "category": "watercolor splash",
    "categoryName": "Watercolor Splash Portrait",
    "subfolder": "Couple",
    "title": "Custom Couple Watercolor Splash Portrait",
    "media": [
      "Products/Water Splash/Couple/1.png",
      "Products/Water Splash/Couple/2.png",
      "Products/Water Splash/Couple/3.png",
      "Products/Water Splash/Couple/4.png",
      "Products/Water Splash/Couple/5.png",
      "Products/Water Splash/Couple/6.png",
      "Products/Water Splash/Couple/7.png"
    ],
    "thumbnail": "Products/Water Splash/Couple/1.png",
    "originalPrice": 299,
    "price": 149,
    "rating": 4.5,
    "reviews": 19,
    "description": "An expressive, vibrant watercolor splash portrait of you and your partner as a couple. Features bold organic paint splatters, rich textures, and bright color palettes for a modern artistic look."
  },
  {
    "category": "watercolor splash",
    "categoryName": "Watercolor Splash Portrait",
    "subfolder": "Dog",
    "title": "Custom Dog Watercolor Splash Portrait",
    "media": [
      "Products/Water Splash/Dog/1.png",
      "Products/Water Splash/Dog/2.png",
      "Products/Water Splash/Dog/3.png",
      "Products/Water Splash/Dog/4.png",
      "Products/Water Splash/Dog/5.png",
      "Products/Water Splash/Dog/6.png",
      "Products/Water Splash/Dog/7.png"
    ],
    "thumbnail": "Products/Water Splash/Dog/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.7,
    "reviews": 40,
    "description": "An expressive, vibrant watercolor splash portrait of your beloved dog. Features bold organic paint splatters, rich textures, and bright color palettes for a modern artistic look."
  },
  {
    "category": "watercolor splash",
    "categoryName": "Watercolor Splash Portrait",
    "subfolder": "Family",
    "title": "Custom Family Watercolor Splash Portrait",
    "media": [
      "Products/Water Splash/Family/1.png",
      "Products/Water Splash/Family/2.png",
      "Products/Water Splash/Family/3.png",
      "Products/Water Splash/Family/4.png",
      "Products/Water Splash/Family/5.png",
      "Products/Water Splash/Family/6.png",
      "Products/Water Splash/Family/7.png"
    ],
    "thumbnail": "Products/Water Splash/Family/1.png",
    "originalPrice": 299,
    "price": 149,
    "rating": 4.6,
    "reviews": 84,
    "description": "An expressive, vibrant watercolor splash portrait of your beautiful family. Features bold organic paint splatters, rich textures, and bright color palettes for a modern artistic look."
  },
  {
    "category": "watercolor splash",
    "categoryName": "Watercolor Splash Portrait",
    "subfolder": "Friends",
    "title": "Custom Friends Watercolor Splash Portrait",
    "media": [
      "Products/Water Splash/Friends/1.png",
      "Products/Water Splash/Friends/2.png",
      "Products/Water Splash/Friends/3.png",
      "Products/Water Splash/Friends/4.png",
      "Products/Water Splash/Friends/5.png",
      "Products/Water Splash/Friends/6.png",
      "Products/Water Splash/Friends/7.png"
    ],
    "thumbnail": "Products/Water Splash/Friends/1.png",
    "originalPrice": 299,
    "price": 149,
    "rating": 4.6,
    "reviews": 47,
    "description": "An expressive, vibrant watercolor splash portrait of you and your closest friends. Features bold organic paint splatters, rich textures, and bright color palettes for a modern artistic look."
  },
  {
    "category": "watercolor splash",
    "categoryName": "Watercolor Splash Portrait",
    "subfolder": "Grandparents",
    "title": "Custom Grandparents Watercolor Splash Portrait",
    "media": [
      "Products/Water Splash/Grandparents/1.png",
      "Products/Water Splash/Grandparents/2.png",
      "Products/Water Splash/Grandparents/3.png",
      "Products/Water Splash/Grandparents/4.png",
      "Products/Water Splash/Grandparents/5.png",
      "Products/Water Splash/Grandparents/6.png",
      "Products/Water Splash/Grandparents/7.png"
    ],
    "thumbnail": "Products/Water Splash/Grandparents/1.png",
    "originalPrice": 299,
    "price": 149,
    "rating": 4.2,
    "reviews": 21,
    "description": "An expressive, vibrant watercolor splash portrait of your dear grandparents. Features bold organic paint splatters, rich textures, and bright color palettes for a modern artistic look."
  },
  {
    "category": "watercolor splash",
    "categoryName": "Watercolor Splash Portrait",
    "subfolder": "Man",
    "title": "Custom Man Watercolor Splash Portrait",
    "media": [
      "Products/Water Splash/Man/1.png",
      "Products/Water Splash/Man/2.png",
      "Products/Water Splash/Man/3.png",
      "Products/Water Splash/Man/4.png",
      "Products/Water Splash/Man/5.png",
      "Products/Water Splash/Man/6.png",
      "Products/Water Splash/Man/7.png"
    ],
    "thumbnail": "Products/Water Splash/Man/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.2,
    "reviews": 42,
    "description": "An expressive, vibrant watercolor splash portrait of a gentleman. Features bold organic paint splatters, rich textures, and bright color palettes for a modern artistic look."
  },
  {
    "category": "watercolor splash",
    "categoryName": "Watercolor Splash Portrait",
    "subfolder": "Person With Cat",
    "title": "Custom Person with Cat Watercolor Splash Portrait",
    "media": [
      "Products/Water Splash/Person With Cat/1.png",
      "Products/Water Splash/Person With Cat/2.png",
      "Products/Water Splash/Person With Cat/3.png",
      "Products/Water Splash/Person With Cat/4.png",
      "Products/Water Splash/Person With Cat/5.png",
      "Products/Water Splash/Person With Cat/6.png",
      "Products/Water Splash/Person With Cat/7.png"
    ],
    "thumbnail": "Products/Water Splash/Person With Cat/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.3,
    "reviews": 41,
    "description": "An expressive, vibrant watercolor splash portrait of your beloved person with cat. Features bold organic paint splatters, rich textures, and bright color palettes for a modern artistic look."
  },
  {
    "category": "watercolor splash",
    "categoryName": "Watercolor Splash Portrait",
    "subfolder": "Person With dog",
    "title": "Custom Person with Dog Watercolor Splash Portrait",
    "media": [
      "Products/Water Splash/Person With dog/1.png",
      "Products/Water Splash/Person With dog/2.png",
      "Products/Water Splash/Person With dog/3.png",
      "Products/Water Splash/Person With dog/4.png",
      "Products/Water Splash/Person With dog/5.png",
      "Products/Water Splash/Person With dog/6.png",
      "Products/Water Splash/Person With dog/7.png"
    ],
    "thumbnail": "Products/Water Splash/Person With dog/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.5,
    "reviews": 43,
    "description": "An expressive, vibrant watercolor splash portrait of your beloved person with dog. Features bold organic paint splatters, rich textures, and bright color palettes for a modern artistic look."
  },
  {
    "category": "watercolor splash",
    "categoryName": "Watercolor Splash Portrait",
    "subfolder": "Sibling",
    "title": "Custom Sibling Watercolor Splash Portrait",
    "media": [
      "Products/Water Splash/Sibling/1.png",
      "Products/Water Splash/Sibling/2.png",
      "Products/Water Splash/Sibling/3.png",
      "Products/Water Splash/Sibling/4.png",
      "Products/Water Splash/Sibling/5.png",
      "Products/Water Splash/Sibling/6.png",
      "Products/Water Splash/Sibling/7.png"
    ],
    "thumbnail": "Products/Water Splash/Sibling/1.png",
    "originalPrice": 299,
    "price": 149,
    "rating": 4.3,
    "reviews": 44,
    "description": "An expressive, vibrant watercolor splash portrait of siblings. Features bold organic paint splatters, rich textures, and bright color palettes for a modern artistic look."
  },
  {
    "category": "watercolor splash",
    "categoryName": "Watercolor Splash Portrait",
    "subfolder": "Woman",
    "title": "Custom Woman Watercolor Splash Portrait",
    "media": [
      "Products/Water Splash/Woman/1.png",
      "Products/Water Splash/Woman/2.png",
      "Products/Water Splash/Woman/3.png",
      "Products/Water Splash/Woman/4.png",
      "Products/Water Splash/Woman/5.png",
      "Products/Water Splash/Woman/6.png",
      "Products/Water Splash/Woman/7.png"
    ],
    "thumbnail": "Products/Water Splash/Woman/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.8,
    "reviews": 59,
    "description": "An expressive, vibrant watercolor splash portrait of a gentleman. Features bold organic paint splatters, rich textures, and bright color palettes for a modern artistic look."
  },
  {
    "category": "wordart",
    "categoryName": "Word Art",
    "subfolder": "Baby",
    "title": "Custom Baby Word Art",
    "media": [
      "Products/Word Art/Baby/1.png",
      "Products/Word Art/Baby/2.mp4",
      "Products/Word Art/Baby/3.png",
      "Products/Word Art/Baby/4.png",
      "Products/Word Art/Baby/5.png",
      "Products/Word Art/Baby/6.png"
    ],
    "thumbnail": "Products/Word Art/Baby/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.2,
    "reviews": 60,
    "description": "A highly personalized photo collage word art featuring a sweet baby. Multiple photo references are masterfully blended inside custom typographic word shapes for a memorable gift."
  },
  {
    "category": "wordart",
    "categoryName": "Word Art",
    "subfolder": "Cat",
    "title": "Custom Cat Word Art",
    "media": [
      "Products/Word Art/Cat/1.png",
      "Products/Word Art/Cat/2.mp4",
      "Products/Word Art/Cat/3.png",
      "Products/Word Art/Cat/4.png",
      "Products/Word Art/Cat/5.png",
      "Products/Word Art/Cat/6.png"
    ],
    "thumbnail": "Products/Word Art/Cat/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.5,
    "reviews": 29,
    "description": "A highly personalized photo collage word art featuring your beloved cat. Multiple photo references are masterfully blended inside custom typographic word shapes for a memorable gift."
  },
  {
    "category": "wordart",
    "categoryName": "Word Art",
    "subfolder": "Dad",
    "title": "Custom Dad Word Art",
    "media": [
      "Products/Word Art/Dad/1.png",
      "Products/Word Art/Dad/2.mp4",
      "Products/Word Art/Dad/3.png",
      "Products/Word Art/Dad/4.png",
      "Products/Word Art/Dad/5.png",
      "Products/Word Art/Dad/6.png"
    ],
    "thumbnail": "Products/Word Art/Dad/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.4,
    "reviews": 85,
    "description": "A highly personalized photo collage word art featuring a dad. Multiple photo references are masterfully blended inside custom typographic word shapes for a memorable gift."
  },
  {
    "category": "wordart",
    "categoryName": "Word Art",
    "subfolder": "Dog",
    "title": "Custom Dog Word Art",
    "media": [
      "Products/Word Art/Dog/1.png",
      "Products/Word Art/Dog/2.mp4",
      "Products/Word Art/Dog/3.png",
      "Products/Word Art/Dog/4.png",
      "Products/Word Art/Dog/5.png",
      "Products/Word Art/Dog/6.png"
    ],
    "thumbnail": "Products/Word Art/Dog/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.7,
    "reviews": 31,
    "description": "A highly personalized photo collage word art featuring your beloved dog. Multiple photo references are masterfully blended inside custom typographic word shapes for a memorable gift."
  },
  {
    "category": "wordart",
    "categoryName": "Word Art",
    "subfolder": "Home",
    "title": "Custom Home Word Art",
    "media": [
      "Products/Word Art/Home/1.png",
      "Products/Word Art/Home/2.mp4",
      "Products/Word Art/Home/3.png",
      "Products/Word Art/Home/4.png",
      "Products/Word Art/Home/5.png",
      "Products/Word Art/Home/6.png"
    ],
    "thumbnail": "Products/Word Art/Home/1.png",
    "originalPrice": 299,
    "price": 149,
    "rating": 4.6,
    "reviews": 71,
    "description": "A highly personalized photo collage word art featuring your cozy home. Multiple photo references are masterfully blended inside custom typographic word shapes for a memorable gift."
  },
  {
    "category": "wordart",
    "categoryName": "Word Art",
    "subfolder": "Love",
    "title": "Custom Love Word Art",
    "media": [
      "Products/Word Art/Love/1.png",
      "Products/Word Art/Love/2.mp4",
      "Products/Word Art/Love/3.png",
      "Products/Word Art/Love/4.png",
      "Products/Word Art/Love/5.png",
      "Products/Word Art/Love/6.png"
    ],
    "thumbnail": "Products/Word Art/Love/1.png",
    "originalPrice": 299,
    "price": 149,
    "rating": 4.5,
    "reviews": 84,
    "description": "A highly personalized photo collage word art featuring a custom love illustration. Multiple photo references are masterfully blended inside custom typographic word shapes for a memorable gift."
  },
  {
    "category": "wordart",
    "categoryName": "Word Art",
    "subfolder": "Mom",
    "title": "Custom Mom Word Art",
    "media": [
      "Products/Word Art/Mom/1.png",
      "Products/Word Art/Mom/2.mp4",
      "Products/Word Art/Mom/3.png",
      "Products/Word Art/Mom/4.png",
      "Products/Word Art/Mom/5.png",
      "Products/Word Art/Mom/6.png"
    ],
    "thumbnail": "Products/Word Art/Mom/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.8,
    "reviews": 46,
    "description": "A highly personalized photo collage word art featuring a mom. Multiple photo references are masterfully blended inside custom typographic word shapes for a memorable gift."
  },
  {
    "category": "wordart",
    "categoryName": "Word Art",
    "subfolder": "Pet",
    "title": "Custom Pet Word Art",
    "media": [
      "Products/Word Art/Pet/1.png",
      "Products/Word Art/Pet/2.mp4",
      "Products/Word Art/Pet/3.png",
      "Products/Word Art/Pet/4.png",
      "Products/Word Art/Pet/5.png",
      "Products/Word Art/Pet/6.png"
    ],
    "thumbnail": "Products/Word Art/Pet/1.png",
    "originalPrice": 199,
    "price": 99,
    "rating": 4.8,
    "reviews": 46,
    "description": "A highly personalized photo collage word art featuring your beloved pet. Multiple photo references are masterfully blended inside custom typographic word shapes for a memorable gift."
  }
];